# .graphclientrc.yml
# https://github.com/graphprotocol/graph-client/blob/main/examples/composition/.graphclientrc.yml

sources:
  - name: beefy-clm
    handler:
      graphql:
        endpoint: https://api.0xgraph.xyz/subgraphs/name/beefyfinance/clm-{context.chainName:arbitrum}
    transforms:
      - autoTypeMerging: true

documents:
  - ./src/queries/*.graphql
