# .graphclientrc.yml
sources:
  - name: beefy-cl
    handler:
      graphql:
        endpoint: https://api.0xgraph.xyz/subgraphs/name/beefyfinance/beefy-cl


documents:
  - ./src/queries/protocol-dashboard.graphql
  - ./src/queries/vault-list.graphql
  - ./src/queries/vault.graphql
  - ./src/queries/investor-list.graphql
  - ./src/queries/investor-dashboard.graphql
  - ./src/queries/position-dashboard.graphql