/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const VaultIndexLazyImport = createFileRoute('/vault/')()
const ProtocolTimeseriesLazyImport = createFileRoute('/protocol/timeseries')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const VaultIndexLazyRoute = VaultIndexLazyImport.update({
  path: '/vault/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/vault/index.lazy').then((d) => d.Route))

const ProtocolTimeseriesLazyRoute = ProtocolTimeseriesLazyImport.update({
  path: '/protocol/timeseries',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/protocol/timeseries.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/protocol/timeseries': {
      preLoaderRoute: typeof ProtocolTimeseriesLazyImport
      parentRoute: typeof rootRoute
    }
    '/vault/': {
      preLoaderRoute: typeof VaultIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ProtocolTimeseriesLazyRoute,
  VaultIndexLazyRoute,
])

/* prettier-ignore-end */
