/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const VaultsLazyImport = createFileRoute('/vaults')()
const InvestorsLazyImport = createFileRoute('/investors')()
const IndexLazyImport = createFileRoute('/')()
const InvestorAddressLazyImport = createFileRoute('/investor/$address')()
const VaultChainAddressLazyImport = createFileRoute('/vault/$chain/$address')()
const InvestorPositionIdLazyImport = createFileRoute('/investor/position/$id')()

// Create/Update Routes

const VaultsLazyRoute = VaultsLazyImport.update({
  path: '/vaults',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/vaults.lazy').then((d) => d.Route))

const InvestorsLazyRoute = InvestorsLazyImport.update({
  path: '/investors',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/investors.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const InvestorAddressLazyRoute = InvestorAddressLazyImport.update({
  path: '/investor/$address',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/investor.$address.lazy').then((d) => d.Route),
)

const VaultChainAddressLazyRoute = VaultChainAddressLazyImport.update({
  path: '/vault/$chain/$address',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/vault.$chain.$address.lazy').then((d) => d.Route),
)

const InvestorPositionIdLazyRoute = InvestorPositionIdLazyImport.update({
  path: '/investor/position/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/investor.position.$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/investors': {
      preLoaderRoute: typeof InvestorsLazyImport
      parentRoute: typeof rootRoute
    }
    '/vaults': {
      preLoaderRoute: typeof VaultsLazyImport
      parentRoute: typeof rootRoute
    }
    '/investor/$address': {
      preLoaderRoute: typeof InvestorAddressLazyImport
      parentRoute: typeof rootRoute
    }
    '/investor/position/$id': {
      preLoaderRoute: typeof InvestorPositionIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/vault/$chain/$address': {
      preLoaderRoute: typeof VaultChainAddressLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  InvestorsLazyRoute,
  VaultsLazyRoute,
  InvestorAddressLazyRoute,
  InvestorPositionIdLazyRoute,
  VaultChainAddressLazyRoute,
])

/* prettier-ignore-end */
